# Makefile for examples

capdimens:;  mkdrawf src.capdimens  drawf.capdimens
convert:;    mkdrawf src.convert    draw.convert
implicit:;   mkdrawf src.implicit   draw.implicit
include:;    mkdrawf src.include    draw.include
infix:;      mkdrawf src.infix      draw.infix
macroparam:; mkdrawf src.macroparam draw.macroparam
newarc:;     mkdrawf src.newarc     drawf.newarc
random:;     mkdrawf src.random     draw.random
shading:;    mkdrawf src.shading    draw.shading
sprite:;     mkdrawf src.sprite     draw.sprite
text:;       mkdrawf src.text       draw.text
textbbox:;   mkdrawf src.textbbox   draw.textbbox
units:;      mkdrawf src.units      draw.units

d_penrose:;  decdrawf draw.penrose  >dec.penrose
d_prism:;    decdrawf draw.prism    >dec.prism
d_sprites:;  decdrawf draw.sprites  >dec.sprites
d_summer:;   decdrawf draw.summer   >dec.summer -s dec.sumSprites
