#!<perl$dir>.perl

# Split a DDF file produced by "makemanual" into contents, main text and index.

($in, $con, $out, $idx) = @ARGV;
open IN,  "<$in"  or die "! Couldn't open input file.\n";
open OUT, ">$out" or die "! Couldn't open main output file.\n";

while (<IN>) {
  last if /on\}Contents\n/;
  print OUT;
}

close OUT;

open CON, ">$con" or die "! Couldn't open contents output file.\n";
print CON;

while (<IN>) {
  last if /on\}Index\n/;
  print CON;
}

close CON;

open IDX, ">$idx" or die "! Couldn't open index output file.\n";
print IDX;
while (<IN>) {
  print IDX;
}

close IDX;

close IN;
